Project management: add user manual pdf.
agiledev3/buyers-remorse-app pull request #33
Opened 2021-03-14 11:24 UTC by dmytrokulak

2021-03-15 05:01 UTC, dmytrokulak commented
@magg01 Please merge it together with https://github.com/agiledev3/buyers-remorse-app/pull/12 if it is ok. 
Original doc is in [g-drive ](https://docs.google.com/document/d/1Trw387U1WVKU16DF8rku50RbhcyABRrvTmEyZALrMvA/edit)

2021-03-16 09:30 UTC, magg01 requested changes
Looks good. I've added some small language and formatting changes to the original document. I did it in edit mode rather than as suggestions for speed. Could you check you're happy with what I did and push a new commit for this version and then I'll merge.

2021-03-16 09:42 UTC, dmytrokulak commented
@magg01 Thank you for editing. Pushed a commit with the updated pdf.

2021-03-16 09:44 UTC, magg01 approved these changes

2021-03-16 09:46 UTC, merged